freeipa/freeipa-container

- Dockerfile.centos-7
- Dockerfile.centos-7-upstream
CentOS 7.3.1611 was released with IPA 4.4.
> Update for CentOS 7.3

- Dockerfile
Please merge after https://github.com/freeipa/freeipa-container/pull/103 gets in.
> Make Fedora 25 the default.

- Dockerfile.fedora-25-master-nightly
bz1377973 has been fixed in freeipa upstream git
> Remove workaround 1377973 from master container

- ipa-server-configure-first
bind-dyndb-ldap must be upgraded too
> Run bind-dyndb-ldap upgrades in container

- Dockerfile.centos-7
> copy changes from rhel7 dockerfile

- install.sh
generalize NET_HOST_PARAM so arbitrary user defined networks (for instance macvlan) can be used
> generalize NET_HOST_PARAM to NET_PARAM

- Dockerfile.fedora-27
- Dockerfile.fedora-rawhide
This PR updates the Dockerfile for Fedora-rawhide and branches Fedora 27 image from it.
> Add a Fedora 27 container

- ipa-server-configure-first
Attempt to address https://github.com/freeipa/freeipa-container/issues/135#issuecomment-349131214.
Untested.
> Support cases when the IPA server happens to resolve multiple addresses.

- .travis.yml
* Check that we only change Dockerfiles that we test with Travis CI.
* Run separate build jobs for each Dockerfile.
* If only tracked Dockerfile is modified, only run the `docker build` for that Dockerfile.
> Travis improvements.

- .travis.yml
This pull request is on top of https://github.com/freeipa/freeipa-container/pull/217.
> Run the containers with docker run in Travis CI.

- .travis.yml
- Dockerfile.centos-7
- Dockerfile.fedora-23
- Dockerfile.fedora-24
- Dockerfile.fedora-25
- Dockerfile.fedora-26
- Dockerfile.fedora-27
- Dockerfile.fedora-28
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-7
- README
- exit-status.conf
- init-data
- ipa-server-configure-first
- ipa-server-configure-first.service
- ipa-server-status-check
- ipa-server-upgrade.service
- systemctl-exit-with-status
This is on top of https://github.com/freeipa/freeipa-container/pull/218.
> Drive exit/no-exit via /run/systemd overrides.

- init-data
init-data: small comment to explain the upgrade process
> Add comment to explain the upgrade process

- Dockerfile.centos-7
- Dockerfile.fedora-23
- Dockerfile.fedora-24
- Dockerfile.fedora-25
- Dockerfile.fedora-26
- Dockerfile.fedora-27
- Dockerfile.fedora-28
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-7
Addressing primarily
```
C /var/lib/rpm
D /var/lib/rpm/__db.001
D /var/lib/rpm/__db.002
D /var/lib/rpm/__db.003
```
> Minimize docker diff upon startup by doing the changes in build time.

- Dockerfile.centos-7
- Dockerfile.fedora-23
- Dockerfile.fedora-24
- Dockerfile.fedora-25
- Dockerfile.fedora-26
- Dockerfile.fedora-27
- Dockerfile.fedora-28
- Dockerfile.fedora-29
- Dockerfile.fedora-30
- Dockerfile.fedora-31
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-7
- Dockerfile.rhel-8
- README
- freeipa-server-openshift.json
- install.sh
Fixes https://github.com/freeipa/freeipa-container/issues/287.
> Update lists of ports that need to be exposed.

- ipa-server-configure-first
Check if pki-tomcat file exists before trying to sed it on
container upgrade.
Fixes #307
> Fix upgrade on ca-less systems

- Dockerfile.centos-8
- Dockerfile.centos-8-stream
- Dockerfile.fedora-33
- Dockerfile.fedora-34
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-8
- tests/run-master-in-k3s.sh
Fixes https://github.com/freeipa/freeipa-container/issues/416.
> Install messages files to support WebUI localization via browser settings (Accept-Language HTTP request header).

- freeipa-server-openshift.json
> Update the OCP template to the correct apiVersion value

- freeipa-server-openshift-image.json
Same as #490, but for the freeipa-server-openshift-image.
> Update the OCP apiVersion value

- Dockerfile.almalinux-9
- Dockerfile.centos-9-stream
- Dockerfile.fedora-38
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-9
- Dockerfile.rocky-9
Fixes https://github.com/freeipa/freeipa-container/issues/527.
> Add the Expiring Password Notification (EPN) tool.

- README
Fixes https://github.com/freeipa/freeipa-container/issues/645.
> Add link to the FreeIPA Documentation page.

- DefaultLimitNOFILE.conf
- Dockerfile.almalinux-9
- Dockerfile.centos-9-stream
- Dockerfile.fedora-40
- Dockerfile.fedora-41
- Dockerfile.fedora-rawhide
- Dockerfile.rhel-9
- Dockerfile.rocky-9
Fixes https://github.com/freeipa/freeipa-container/issues/653.
> Set the NOFILE hard limit to the value we see on host installations
