Dockerfile
It looks like the default configuration now requires the freeipa-server-dns package to configure properly.
=> Fix missing freeipa-server-dns package

ipa-server-configure-first
With the current code, that two-phase --external-ca / --external-cert-file workflow was not supported well. With this set of patches, first time the container is run with --external-ca, ipa.csr is stored in the /data volume. The second time the container is run with --external-cert-file parameters pointing to the external CA certificate and the new IPA server certificate, it will continue with the configuration of the outstanding components, including the DNS server that https://github.com/freeipa/freeipa-container/issues/14 reports failing.
=> Fix 14: support the --external-ca workflow.

Dockerfile.centos-7, Dockerfile.centos-7-upstream, Dockerfile.fedora-23, Dockerfile.fedora-23-upstream, Dockerfile.fedora-24, Dockerfile.fedora-25, Dockerfile.fedora-rawhide, Dockerfile.rhel-7, Dockerfile.rhel-7-upstream, ipa-server-configure-first
This will populate /data-template which will use the standard mechanism for installation and upgrades to populate /data.
=> Create parent dirs for volume-data-list in build time.

Dockerfile.fedora-25-master-nightly
This Dockerfile is required for the early testing of the influence of
the current devel snapshots of FreeIPA on the stability of the container
image.
The images build from this Dockerfile should not be pushed to registry.
Since it contains development snapshots you need to rebuild it often
anyway.
=> Introduce a Dockerfile using Fedora 25 nightly builds of FreeIPA master

Dockerfile.fedora-25, Dockerfile.fedora-25-master-nightly, Dockerfile.fedora-rawhide
SSSD 1.15.1 introduced changes into it's drop-in journal configuration
that cause image build to fail on SHA1 checksum mismatch. Introduce a
correct reference checksum so that the build can continue.
=> Fix build of F25-nightly and rawhide images due to SSSD update

Dockerfile.fedora-25-master-nightly
gssproxy requires 'proc-fs-nfsd.mount' target to be enabled in order to
run, which is possible only in privileged containers. To unblock Freeipa
4.5.x installation we have to mask this requirement.
=> mask proc-fs-nfsd.mount requirement of gssproxy in nightly image

Dockerfile.fedora-25-master-nightly
This unblocks F25 nightly image build which was broken by recent changes in the
system user creation.
https://github.com/freeipa/freeipa-container/issues/126
=> Move user/group creation before RPM install and create ipaapi user/group

volume-data-list
This is to preserve the drop-in configuration required by FreeIPA 4.5
and higher due privilege separation work.
=> Add gssproxy configuration to volume data list

Dockerfile.fedora-24, Dockerfile.fedora-25, Dockerfile.fedora-25-master-nightly, Dockerfile.fedora-rawhide
The guidelines document says:
The FROM instruction must be fully-qualified with a registry name, image
name, and tag as shown in this example:
FROM registry.example.com/imagename:tag
=> Use FROM registry.fedoraproject.org/fedora per https://fedoraproject.org/wiki/Container:Guidelines.

freeipa-server-openshift.json
The default 10 minute timeout might be too low in some testing environment (slow network to download the image, slow CPU to run full ipa-server-install).
=> Add TIMEOUT parameter for update acceptor timeout.

Dockerfile.fedora-25-master-nightly
Freeipa-devel mailing list has been migrated to
freeipa-devel@lists.fedorahosted.org
=> Update freeipa-devel email

Dockerfile.fedora-25, Dockerfile.fedora-26
In FreeIPA 4.4, validation of ip-address slightly changed so we have to
extend workaround.
=> Extend non-local ip addresses workaround bz#1377973

Dockerfile.fedora-rawhide
Similar to 83caaf36e1c8b1405edfaa346f20cf49bb707788.
Addressing
```
Step 29 : RUN groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy
---> Running in ba7a5b8b83fe
groupadd: group 'kdcproxy' already exists
useradd: group '288' does not exist
The command '/bin/sh -c groupadd -g 288 kdcproxy ; useradd -u 288 -g 288 -c 'IPA KDC Proxy User' -d '/var/lib/kdcproxy' -s '/sbin/nologin' kdcproxy' returned a non-zero code: 6
```
=> Ensure stable UIDs/GIDs, something that sadly rpms do not provide.

README, init-data, ipa-server-configure-first
Add two environment variables that may be defined with `docker run -e`
to aid debugging:
- Define `$DEBUG_TRACE` to turn on `init-data` and
`ipa-server-configure-first` script tracing
- Define `$DEBUG_NO_EXIT` to disable container exit after failures
=> Add script debugging options

Dockerfile.fedora-25-master-nightly, Dockerfile.fedora-rawhide
Changes in f26 and later `389-ds-base` add `/usr/share/dirsrv/schema`
to packaging, which breaks the Dockerfile `/etc/dirsrv/schema`
relocation.
Instead of moving the whole directory, move just the contents.
Related to #157, "Support for FreeIPA v. 4.5".
=> Fix `/etc/dirsrv/schema` relocation

Dockerfile.fedora-26
Untested, should be mostly equivalent to https://github.com/freeipa/freeipa-container/pull/161.
This should make `docker diff` pass, at least on Fedora 25 hosts.
=> Avoid runtime changes in /var/lib/dbus/machine-id.

Dockerfile.fedora-26-master-nightly
The @freeipa/freeipa-master copr repo does not offer rpms for
Fedora 25 anymore, switch to Fedora 26 instead.
=> Make Fedora 26 the base for nightly container

Dockerfile.fedora-26-master-nightly
SSSD no longer uses journal.conf, build fails on sha1sum check
=> f26nightly: Remove sha1sum check of sssd journal.conf

Dockerfile.fedora-25, Dockerfile.fedora-26, Dockerfile.fedora-26-master-nightly, Dockerfile.fedora-27, Dockerfile.fedora-rawhide
This removes the workaround originally introduced for
https://bugzilla.redhat.com/show_bug.cgi?id=1343129 which seems to
be fixed now.
=> Remove workaround configuring locale

Dockerfile
Fedora 25 is reaching EOL and freeIPA Fedora 26 image seems to be
stable, mark it as latest.
=> Make Dockerfile point to Dockerfile.fedora-26

Dockerfile.fedora-25, Dockerfile.fedora-26, Dockerfile.fedora-27, Dockerfile.fedora-rawhide
SSSD no longer uses journal.conf, build fails on sha1sum check of
this file.
=> Remove sha1sum check of sssd journal.conf

Dockerfile.fedora-rawhide
Fedora rawhide container does have empty /etc/tmpfiles.d/ and opendnssec.conf is already in /usr/lib/tmpfiles.d/
=> Removes checking /etc/tmpfiles.d/ for opendnssec.conf

Dockerfile.fedora-26, Dockerfile.fedora-26-master-nightly, Dockerfile.fedora-27
Fedora 26 & 27 container does have opendnssec.conf in /usr/lib/tmpfiles.d/ too now
https://github.com/freeipa/freeipa-container/pull/181
=> Remove checking /etc/tmpfiles.d/ for opendnssec.conf in F26&27

ipa-server-configure-first.service
OpenSSL requires at least one of HOME or RANDFILE environment
variables to be set for it to work.
Without this fix, the external CA setup crashes because OpenSSL
is unable to write its random state anywhere when it tries to
generate a CSR for the external CA to sign.
=> Add HOME env var to ipa-server-configure.service

Dockerfile.centos-7, Dockerfile.centos-7-upstream, Dockerfile.fedora-23, Dockerfile.fedora-23-upstream, Dockerfile.fedora-24, Dockerfile.fedora-25, Dockerfile.fedora-26, Dockerfile.fedora-26-master-nightly, Dockerfile.fedora-27, Dockerfile.fedora-rawhide, Dockerfile.rhel-7, Dockerfile.rhel-7-upstream
This reverts commit ede29f7531fad3ff38dee7634e3eefc8530bed8c.
Addressing buildah build issue
```
STEP 39: VOLUME [ "/tmp", "/run", "/data", "/var/log/journal" ]
error building: error building at step {Env:[container=docker DISTTAG=f26container FGC=f26   PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=docker] Command:volume Args:[/tmp /run /data /var/log/journal] Flags:[] Attrs:map[json:true] Message:VOLUME /tmp /run /data /var/log/journal Original:VOLUME [ "/tmp", "/run", "/data", "/var/log/journal" ]}: error ensuring volume path "/var/lib/containers/storage/overlay/6316033d1eacdd9a3e2065019bf8b196b057fa36326980f2760f51f2b40f4910/merged/var/log/journal" exists: mkdir /var/lib/containers/storage/overlay/6316033d1eacdd9a3e2065019bf8b196b057fa36326980f2760f51f2b40f …
```
=> Revert "Let oci-systemd-hook create journal directory before /data is mounted.

Dockerfile.rhel-7
/etc/systemd/system/sssd.service.d/journal.conf is no longer
present in RHEL7 base image.
=> Remove sha1sum from RHEL7 dockerfile

Dockerfile
Fedora 26 is reaching EOL and Fedora 27 image seems to be stable, mark
it as the default.
=> Make Dockerfile point to Dockerfile.fedora-27.

Dockerfile.fedora-27
Addressing
```
Step 6/46 : RUN mkdir -p /var/lib/dbus && ln -s /etc/machine-id /var/lib/dbus/machine-id
---> Running in 2c0b201b759b
ln: failed to create symbolic link '/var/lib/dbus/machine-id': File exists
```
The symlink gets created by `systemd`'s postinstall scriptlet calling `systemd-tmpfiles --create` during the previous `dnf upgrade` step.
=> Do not create /var/lib/dbus/machine-id symlink if it already exists.

Dockerfile.fedora-rawhide
Addressing
```
No repository match: rawhide-modular
```
=> The rawhide-modular repo seems no more.

Dockerfile.fedora-rawhide, hostnamectl-wrapper
Fedora rawhide uses `nis-domainname.service` instead of `fedora-domainname.service`.
It in turn invokes `/usr/libexec/hostname/nis-domainname` which then calls `nisdomainname`, instead of `/usr/lib/systemd/fedora-domainname` which called `/usr/bin/domainname`.
Addressing
```
CalledProcessError(Command ['/bin/systemctl', 'restart', 'nis-domainname.service'] returned non-zero exit status 1: 'Job for nis-domainname.service failed because the control process exited with error code.\nSee "systemctl status nis-domainname.service" and "journalctl -xe" for details.\n')
The ipa-client-install command failed. See /var/log/ipaclient-install.log for more information
ipapython.admintool: ERROR    Configuration of client side components failed!
ipapython.admintool: ERROR    The ipa-server-install …
```
=> Fedora rawhide uses nis-domainname.service instead of fedora-domainname.service.

.travis.yml
Test https://travis-ci.org/freeipa/freeipa-container/builds/400261740 for https://github.com/freeipa/freeipa-container/pull/212 did only run for fedora-rawhide even if  `hostnamectl-wrapper` was also changed. If any non-Dockerfile gets changed, we need to retest everything.
=> If non-Dockerfile was changed, we need to run all tests.

Dockerfile.fedora-rawhide
Addressing
```
Step 6/44 : RUN sed -i '/installutils.verify_fqdn(config.master_host_name, options.no_host_dns)/s/)/, local_hostname=False)/' /usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py && python3 -m compileall /usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py
---> Running in e5784e069cc3
sed: can't read /usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py: No such file or directory
The command '/bin/sh -c sed -i '/installutils.verify_fqdn(config.master_host_name, options.no_host_dns)/s/)/, local_hostname=False)/' /usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py && python3 -m compileall /usr/lib/python3.6/site-packages/ipaserver/install/server/replicainstall.py' returned a non-zero …
```
=> Fedora rawhide now has python 3.7.

ipa-server-configure-first, tests/build-and-run.sh
Fixes https://github.com/freeipa/freeipa-container/issues/214.
=> The ipaplatform was refactored on Fedora 27, just decide about the platform ourselves.

.travis.yml
Avoiding
```
[1/44]: creating directory server instance
[error] FileNotFoundError: [Errno 2] No such file or directory: '/usr/sbin/setup-ds.pl': '/usr/sbin/setup-ds.pl'
FreeIPA server configuration failed.
```
and
```
[error] RuntimeError: failed to create DS instance CalledProcessError(Command ['/usr/sbin/setup-ds.pl', '--silent', '--logfile', '-', '-f', '/tmp/tmpls_vesa4'] returned non-zero exit status 1: '')
FreeIPA server configuration failed.
```
=> Workaround 1606541, skip tests on rawhide.

init-data, ipa-server-configure-first, ipa-server-upgrade.service
When services are running when FreeIPA upgrade starts, we see too many failures when upgrading to Fedora 27 and 28.
=> Upgrade from stopped services

init-data, ipa-server-configure-first, ipa-server-upgrade.service
Upgrading to Fedora 26 or newer, `sed -i.bak` on `/etc/named.conf` from rpm scriptlets would modify the symlink, not the underlying file on `/data`, and produce
```
C /etc/named.conf
C /etc/named.conf.bak
```
`docker diff` output.
=>  The /etc/named.conf is symlink to /data, avoid changing it.

Dockerfile.fedora-27
Addressing
```
Step 7/47 : RUN sed -i '/installutils.verify_fqdn(config.master_host_name, options.no_host_dns)/s/)/, local_hostname=False)/' /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py && python -m compileall /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py
---> Running in 34a5865821d8
sed: can't read /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py: No such file or directory
The command '/bin/sh -c sed -i '/installutils.verify_fqdn(config.master_host_name, options.no_host_dns)/s/)/, local_hostname=False)/' /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py && python -m compileall /usr/lib/python2.7/site-packages/ipaserver/install/server/replicainstall.py' returned a non-zero …
```
=> The python2-ipaserver no longer seems being installed.

.travis.yml, README, ipa-server-configure-first, tests/run-master-and-replica.sh
The goal was to avoid writing to overlay and they copying the changes to `/data`. We monkey-patch in build time paths that the software uses to make it work with `/data` directly.
=> [WIP, do not merge] Massive amount of changes to make FreeIPA container runnable as --read-only.

patches/ipa-fedora-30.patch
With new release of freeipa 4.8.0 patching
kernel_keyring.py is no longer necessary
See: https://github.com/freeipa/freeipa/pull/2677
=> Remove persitent keyring workaround patch for f30 and rawhide

Dockerfile.rhel-7
Edit: The workaround to create 389 user is no longer needed,
removing from the Dockerfile.rhel-7
With updated RHEL 7.7 we are unable to patch file
tmpfiles.d/opencryptoki.conf so removing
basic-centos-7.patch from Dockerfile.rhel-7.
Refreshing ipa-rhel-7.patch for kernel_keyring.py
in ipa-rhel-7.patch due to changes in IPA.
=> Update for RHEL 7.7

Dockerfile.centos-7, Dockerfile.fedora-23, Dockerfile.fedora-24, Dockerfile.fedora-25, Dockerfile.fedora-26, Dockerfile.fedora-27, Dockerfile.fedora-28, Dockerfile.fedora-29, Dockerfile.fedora-30, Dockerfile.fedora-rawhide, Dockerfile.rhel-7, Dockerfile.rhel-8, certmonger-wait-for-ready.conf
Fixes https://github.com/freeipa/freeipa-container/issues/187.
=> Workaround 1656519 - set the ulimit in the container to reasonably low value.

freeipa-server-openshift.json
Resolves #289 
This fixes the issue that was seen when processing the openshift template on OCP 4.X.
=> Fix openshift template to work appropriately on OCP 4.X

patches/ipa-fedora-30.patch, patches/ipa-fedora-32.patch
FreeIPA 4.8.1+ has patch for container's
environment with not namespaced keyrings.
=> Do not patch krb5.conf for FreeIPA 4.8.1+

Dockerfile.centos-8
Twelve days ago Travis CI run with CentOS 8-based containers passed: https://travis-ci.org/freeipa/freeipa-container/builds/598071630.
Today it failed: https://travis-ci.org/adelton/freeipa-container/jobs/603565501. The error seems similar to https://bugs.centos.org/view.php?id=16655 and even installing the package before the module operation helps as a workaround.
=> Workaround https://bugs.centos.org/view.php?id=16655.

patches/ipa-data-centos-7.patch, patches/ipa-data-centos-8.patch, patches/ipa-data-fedora-23.patch, patches/ipa-data-fedora-24.patch, patches/ipa-data-fedora-25.patch, patches/ipa-data-fedora-27.patch, patches/ipa-data-fedora-28.patch, patches/ipa-data-fedora-29.patch, patches/ipa-data-fedora-30.patch, patches/ipa-data-fedora-32.patch, patches/ipa-data-rhel-8.patch, tests/run-master-and-replica.sh, tests/systemd-container-ipa-server-install-data.sh, volume-data-list
Addressing `ipa-adtrust-install` failing with
```
[5/24]: creating samba config registry
[error] CalledProcessError: CalledProcessError(Command ['/usr/bin/net', 'conf', 'import', '/tmp/tmpi97o8hgm'] returned non-zero exit status 255: 'Failed to initialize the registry: WERR_NOT_ENOUGH_MEMORY\n')
```
Fixes https://github.com/freeipa/freeipa-container/issues/280.
=> Add support for ipa-adtrust-install with /data volume.

patches/ipa-rhel-7.patch
Remove workaround for persistent keyring krb5.conf and ipa-replica-install because latest RHEL 7.8 release has this patched in ipa-[server|replica]-install.
Signed-off-by: Tibor Dudlák <tdudlak@redhat.com>
=> Remove workaround for persistent keyring krb5.conf and ipa-replica-install

Dockerfile.centos-8, Dockerfile.fedora-32, Dockerfile.fedora-rawhide, Dockerfile.rhel-8, journald-storage.conf, patches/ipa-data-fedora-32.patch, patches/ipa-data-fedora-33.patch, patches/ipa-data-rhel-8.patch
There is no need to patch global journald.conf file. journald reads
configuration snippets from /usr/lib/systemd/journald.conf.d/*.conf.
Signed-off-by: Christian Heimes <cheimes@redhat.com>
=> Configure journald storage with drop-in file

tests/run-master-and-replica.sh, tests/systemd-container-ipa-server-install-data.sh
The test suite no longer prints an error message like
ls: cannot access '/var/log/journal/a3bd8db7322543a98dd75d2485d51ec5': No such file or directory
when it checks for a local mount point on the host file system.
See: https://github.com/freeipa/freeipa-container/pull/335
Signed-off-by: Christian Heimes <cheimes@redhat.com>
=> Silence error message in journald check

Dockerfile.fedora-32, README, init-data, tests/docker-diff-ipa.out, tests/run-master-and-replica.sh, tests/systemd-container-ipa-server-install-data.sh, volume-data-list
D-Bus requires a proper /etc/machine-id to work. The file
/etc/machine-id is empty by default. In a read-only container D-Bus is
unable to create machine-id in /etc/ or /var/lib/dbus/ and then fails
with a cryptic error message:
ERROR launcher_run_child @ ../src/launch/launcher.c +325: No medium found
The init-data script now creates a /data/etc/machine-id when the file
does not exist and /etc/machine-id is a symlink. By default
/etc/machine-id is a symlink to /data/etc/machine-id. Container runtimes
are still free to bind-mount a custom /etc/machine-id.
Signed-off-by: Christian Heimes <cheimes@redhat.com>
=> Create machine-id early

README, tests/run-master-and-replica.sh, tests/run-partial-tests.sh
Fixes https://github.com/freeipa/freeipa-container/issues/186.
=> Document podman invocation in README, use the documented parameters in tests.

.github/workflows/build-test.yaml
With this change the same images that are used for tests in the master branch will be pushed to the Docker Hub.
We'd need `DOCKER_USERNAME` and `DOCKER_PASSWORD` secrets in this repository set to some account which can push to https://hub.docker.com/r/freeipa/freeipa-server. Also, the automatic builds in https://hub.docker.com/r/freeipa/freeipa-server that (I assume) are now run from https://github.com/Tiboris/freeipa-container should be disabled.
The pull request shows pushing Fedora 32, rawhide, CentOS 8 and 7 images. Based on proposal in https://github.com/freeipa/freeipa-container/issues/343#issuecomment-688650487 we do not push `:latest` here and maybe we should just delete it from the Docker Hub? I can add pushing Fedora 31 if we find it useful.
I've tested this change on my fork …
=> Push built images to Docker Hub when tests pass

.github/workflows/build-test.yaml
Besides tags like `freeipa/freeipa-server:fedora-32`, additional tags with the FreeIPA version like `freeipa/freeipa-server:fedora-32-4.8.9` will be created in the Docker Hub repository after each successful CI run on master.
Fixes https://github.com/freeipa/freeipa-container/issues/246.
Fixes https://github.com/freeipa/freeipa-container/issues/343.
=> Also tag the images in Docker Hub with FreeIPA version in the image.

patches/ipa-data-fedora-32.patch, patches/ipa-data-fedora-33.patch, patches/ipa-data-rhel-8.patch
Addressing failure in read-only containers
```
[Errno 30] Read-only file system: '/var/log/ipabackup.log'.
```
Fixes https://github.com/freeipa/freeipa-container/issues/347.
I only add the patch to the current/future OS versions because I don't consider it critical.
=> Point ipa-backup and ipa-restore log location to /data.

.github/workflows/build-test.yaml
The following secrets need to be set in GitHub for the repository
for push to work:
`REGISTRY_TARGET_LIST` with list of target repositories:
```
docker://docker.io/freeipa/freeipa-server
docker://quay.io/freeipa/freeipa-server
```
`REGISTRY_CREDENTIALS_FILE` which is what `docker login` produces:
```
{ "auths": { "docker.io": { "auth": "password-for-docker" }, "quay.io": { "auth": "password-for-quay" } } }
```
=> Support pushing images to multiple registries.

ipa-server-configure-first
This should address the issue of attempted modification of resolv.conf on read-only setups.
Fixes https://github.com/freeipa/freeipa-container/issues/413.
=> If resolv.conf is the same as we saw it right after installation, we likely can use it as is.

tests/run-master-and-replica.sh, volume-data-list
Also adding it to CI jobs in `tests/run-master-and-replica.sh`.
Fixes https://github.com/freeipa/freeipa-container/issues/471.
=> Enable running ipa-kra-install with read-only setup.

.github/workflows/build-test.yaml, Dockerfile.almalinux-8, Dockerfile.almalinux-9, Dockerfile.centos-8, Dockerfile.centos-8-stream, Dockerfile.centos-9-stream, Dockerfile.fedora-26, Dockerfile.fedora-27, Dockerfile.fedora-28, Dockerfile.fedora-29, Dockerfile.fedora-30, Dockerfile.fedora-31, Dockerfile.fedora-32, Dockerfile.fedora-33, Dockerfile.fedora-34, Dockerfile.fedora-35, Dockerfile.fedora-36, Dockerfile.fedora-37, Dockerfile.fedora-38, Dockerfile.fedora-rawhide, Dockerfile.rhel-7, Dockerfile.rhel-8, Dockerfile.rhel-9, Dockerfile.rocky-8, Dockerfile.rocky-9
Addressing
```
[wsgi:alert] [pid 162742:tid 162742] (2)No such file or directory: mod_wsgi (pid=162742): Unable to change working directory to home directory '/var/lib/kdcproxy' for uid=288. [wsgi:alert] [pid 162742:tid 162742] mod_wsgi (pid=162742): Failure to configure the daemon process correctly and process left in unspecified state. Restarting daemon process after delay.
```
Fixes https://github.com/freeipa/freeipa-container/issues/551.
=> Fix start of kdcproxy in mod_wsgi.

ipa-server-configure-first
Testing https://github.com/freeipa/freeipa-container/pull/624 (on the original PR, I don't seem to get "Approve and run" button -- possibly an instance of https://github.com/orgs/community/discussions/119459).
=> ipa-server-configure-first: add timeout to the host resolution

README, ipa-server-configure-first, tests/freeipa-k3s.yaml, tests/freeipa-replica-k3s.yaml
When an IPv4 address is set using the `ipa-server-install`'s `--ip-address` parameter and the DNS record gets populated with that value, the current logic in `ipa-server-configure-first` rewrites that value after the `ipa-server-install` finishes and then during the subsequent container starts with the current internal IPv4 address of the container. Admins then have to use the `IPA_SERVER_IP` environment variable to force the value to be left alone.
This PR adds support for `IPA_SERVER_IP` value `no-update`, to just leave the DNS records alone during the container startup.
That way, whatever value(s) get set either during the initial `ipa-server-install` or perhaps manually will not get lost.
=> Add support for -e IPA_SERVER_IP=no-update.

ipa-server-configure-first
Hi!
I tested PR https://github.com/freeipa/freeipa-container/pull/640 and saw a not quite correct message during the first freeipa server initialization with the variable IPA_SERVER_IP=no-update
Here is my fixes
=> fix log message on freeipa first start when enable no-update

README, ipa-server-configure-first, tests/run-master-and-replica.sh
Initial deprecation message for https://github.com/freeipa/freeipa-container/issues/644.
=> No longer update `resolv.conf` to point to our own DNS server, let users specify the `--dns=127.0.0.1` explicitly [deprecate first].

DefaultLimitNOFILE.conf, Dockerfile.almalinux-9, Dockerfile.centos-9-stream, Dockerfile.fedora-40, Dockerfile.fedora-41, Dockerfile.fedora-rawhide, Dockerfile.rhel-9, Dockerfile.rocky-9
Using a drop-in file seems like the cleanest approach.
Addressing
```
/etc/systemd/system.conf:1: Assignment outside of section. Ignoring.
```
Fixes https://github.com/freeipa/freeipa-container/issues/652.
=> The /etc/systemd/system.conf in latest Fedoras no longer has the [Manager] section

.github/build-test-params.yaml, .github/workflows/build-test.yaml, .github/workflows/run-partial-tests.yaml, .github/workflows/test-rhel.yaml
I believe that through a series of changes to the test setup in `master` we now have a baseline for being able to add additional architecture to the mix beyond x86_64, namely ARM64 (aarch64). Based on announcement in https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/, ARM64 runners are now available so building and testing ARM64 images and combining them into multiarch images (manifests) from a single workflow is now possible.
In this PR I show how we could build and run tests on ARM64 on a subset of architectures, while only pushing to registries multiarch images based on AlmaLinux 9 and Rocky Linux 9. My reason for being conservative with the set of OSes that we would publish is maintenance effort, utility, …
=> Add the ARM architecture to the build and test matrix.

.github/build-test-params.yaml
Resolves https://github.com/freeipa/freeipa-container/issues/664.
=> Expand the upgrade test matrix, RHEL 9-derived images.

ipa-server-configure-first
Fixes https://github.com/freeipa/freeipa-container/issues/644.
In https://github.com/freeipa/freeipa-container/pull/646 we added a note that the current mechanism will be removed in April 2025. This is the removal, so this PR should be rebased and pushed to master in April.
=> No longer update `resolv.conf` to point to our own DNS server, let users specify the `--dns=127.0.0.1` explicitly.

Dockerfile.almalinux-8, Dockerfile.almalinux-9, Dockerfile.centos-10-stream, Dockerfile.centos-9-stream, Dockerfile.fedora-41, Dockerfile.fedora-42, Dockerfile.fedora-rawhide, Dockerfile.rhel-8, Dockerfile.rhel-9, Dockerfile.rocky-8, Dockerfile.rocky-9, tests/run-master-and-replica.sh, tmpfiles-ownership-fedora-40.conf, tmpfiles-ownership-fedora-41.conf
Here's a proposed solution for making uids/gids defined in the Dockerfile/image, and thus static. We only care about ownership of content that lands on the `/data` volume, and we are adding a check to `tests/run-master-and-replica.sh` to catch any runaway content.
Resolves https://github.com/freeipa/freeipa-container/issues/667.
=> Ensure and test that all uids and gids used to store on /data are known and static.

.github/build-test-params.yaml, .github/workflows/build-test.yaml, .github/workflows/run-partial-tests.yaml, Dockerfile.almalinux-10
Comparing https://almalinux.org/get-almalinux/ which lists both AlmaLinux 9.6 and 10 available today, with https://rockylinux.org/download which still lists 9.5 as the latest version, my current plan is to start building, testing, and pushing to registries AlmaLinux 10-based images, for both x86_64 and aarch64 architectures.
At the same time I do not plan to build Rocky Linux 10-based images at all.
Please speak up if you see issues with these plans.
=> Start building FreeIPA on AlmaLinux 10 image.

README
The rendered section can be seen at https://github.com/adelton/freeipa-container/tree/issue-672?tab=readme-ov-file#running-in-kubernetes.
Fixes https://github.com/freeipa/freeipa-container/issues/672.
=> Document running FreeIPA server Pods in Kubernetes.
